name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out the code
        uses: actions/checkout@v5.0.0

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
        id: node

      - name: Get dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          gh release upload ${{ github.event.release.tag_name }} main.js manifest.json
